repos:
- repo: https://github.com/pycqa/isort
  rev: 9.0.0a3
  hooks:
  - id: isort
    args: [--treat-comment-as-code, "# %%", --float-to-top]

- repo: https://github.com/psf/black
  rev: 26.5.1
  hooks:
  - id: black
    language_version: python3